In [1]:
student_per_p = 'student-por.csv'

In [2]:
import pandas as pd

In [3]:
student_per = pd.read_csv(student_per_p, sep=';', decimal='.', header=0, names=['school', 'sex', 'age',
                                                                                  'address', 'famsize',
                                                                                  'pstatus', 'medu', 'fedu',
                                                                                  'mjob', 'fjob', 'reason',
                                                                                  'guardian', 'traveltime',
                                                                                  'studytime', 'failures',
                                                                                  'schoolsup', 'famsup',
                                                                                  'paid', 'activities',
                                                                                  'nursery', 'higher', 'internet',
                                                                                  'romantic', 'famrel', 'freetime',
                                                                                  'goout', 'dalc', 'walc', 'health',
                                                                                  'absences', 'grade1', 'grade2',
                                                                                  'finalgrade'],index_col=False)

In [4]:
#Keep only the columns we are interested in
student_per = student_per.drop(['school', 'sex', 'age', 'famsize', 'medu', 'fedu', 'mjob', 'fjob', 'reason',
                               'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
                               'higher', 'internet', 'freetime', 'goout', 'dalc', 'grade1', 'grade2'], axis=1)

In [5]:
student_per

address pstatus guardian  traveltime romantic  famrel  walc  health  \
0         U       A   mother           2       no       4     1       3   
1         U       T   father           1       no       5     1       3   
2         U       T   mother           1       no       4     3       3   
3         U       T   mother           1      yes       3     1       5   
4         U       T   father           1       no       4     2       5   
5         U       T   mother           1       no       5     2       5   
6         U       T   mother           1       no       4     1       3   
7         U       A   mother           2       no       4     1       1   
8         U       A   mother           1       no       4     1       1   
9         U       T   mother           1       no       5     1       5   
10        U       T   mother           1       no       3     2       2   
11        U       T   father           3       no       5     1       4   
12        U       T   father           1       no       4     3       5   
13        U       T   mother           2       no       5     2       3   
14        U       A    other           1      yes       4     1       3   
15        U       T   mother           1       no       4     2       2   
16        U       T   mother           1       no       3     2       2   
17        U       T   mother           3       no       5     1       4   
18        U       T   mother           1       no       5     4       5   
19        U       T   father           1       no       3     3       5   
20        U       T   mother           1       no       4     1       1   
21        U       T   father           1       no       5     1       5   
22        U       T   mother           1       no       4     3       5   
23        U       T   mother           2       no       5     4       5   
24        R       T   mother           1       no       4     1       5   
25        U       T   mother           1       no       1     3       5   
26        U       T   mother           1       no       4     2       5   
27        U       T   mother           1       no       2     4       1   
28        U       A   mother           1       no       5     1       5   
29        U       T   mother           1      yes       4     5       5   
..      ...     ...      ...         ...      ...     ...   ...     ...   
619       U       T   mother           2      yes       4     3       3   
620       U       T   mother           1      yes       2     1       1   
621       R       T   father           2       no       3     2       3   
622       R       T   mother           2       no       3     4       3   
623       U       T   mother           2      yes       4     2       5   
624       R       T   mother           3      yes       5     2       1   
625       U       T   father           2      yes       5     2       4   
626       R       T   father           3      yes       3     2       5   
627       R       T   father           3      yes       4     3       3   
628       U       T   mother           1      yes       3     1       3   
629       R       T   mother           1       no       3     3       1   
630       R       T   mother           2       no       5     1       1   
631       R       T   mother           4       no       4     2       4   
632       R       T    other           2      yes       4     1       3   
633       R       T   mother           1       no       5     4       2   
634       U       T   mother           1      yes       4     2       1   
635       R       T   mother           1       no       4     3       1   
636       U       T   father           1       no       3     4       2   
637       R       T   mother           2      yes       4     3       5   
638       U       T   father           2       no       4     1       3   
639       R       T   mother           2       no       4     3       5   
640       R       T   father 

In [6]:
import numpy as np

In [7]:
#convert strings into int
student_per['address'] = np.where(student_per['address']== 'U', 1, student_per['address'])
student_per['address'] = np.where(student_per['address'] == 'R', 0, student_per['address'])
student_per['address'].value_counts()

1    452
0    197
Name: address, dtype: int64

In [8]:
student_per['pstatus'] = np.where(student_per['pstatus'] == 'A', 0, student_per['pstatus'])
student_per['pstatus'] = np.where(student_per['pstatus'] == 'T', 1, student_per['pstatus'])
student_per['pstatus'].value_counts()

1    569
0     80
Name: pstatus, dtype: int64

In [9]:
student_per['guardian'] = np.where(student_per['guardian'] == 'mother', 0, student_per['guardian'])
student_per['guardian'] = np.where(student_per['guardian'] == 'father', 1, student_per['guardian'])
student_per['guardian'] = np.where(student_per['guardian'] == 'other', 2, student_per['guardian'])
student_per['guardian'].value_counts()

0    455
1    153
2     41
Name: guardian, dtype: int64

In [10]:
student_per['romantic'] = np.where(student_per['romantic'] == 'no', 0, student_per['romantic'])
student_per['romantic'] = np.where(student_per['romantic'] == 'yes', 1, student_per['romantic'])
student_per['romantic'].value_counts()

0    410
1    239
Name: romantic, dtype: int64

In [11]:
#get target values, split grades
student_per['finalgrade'] = np.where(student_per['finalgrade'].between(0,4), 0, student_per['finalgrade'])
student_per['finalgrade'] = np.where(student_per['finalgrade'].between(5,9), 1, student_per['finalgrade'])
student_per['finalgrade'] = np.where(student_per['finalgrade'].between(10,14), 2, student_per['finalgrade'])
student_per['finalgrade'] = np.where(student_per['finalgrade'].between(15,20), 3, student_per['finalgrade'])
 
student_per['finalgrade'].value_counts()

2    418
3    131
1     84
0     16
Name: finalgrade, dtype: int64

In [12]:
student_per

address pstatus guardian  traveltime romantic  famrel  walc  health  \
0         1       0        0           2        0       4     1       3   
1         1       1        1           1        0       5     1       3   
2         1       1        0           1        0       4     3       3   
3         1       1        0           1        1       3     1       5   
4         1       1        1           1        0       4     2       5   
5         1       1        0           1        0       5     2       5   
6         1       1        0           1        0       4     1       3   
7         1       0        0           2        0       4     1       1   
8         1       0        0           1        0       4     1       1   
9         1       1        0           1        0       5     1       5   
10        1       1        0           1        0       3     2       2   
11        1       1        1           3        0       5     1       4   
12        1       1        1           1        0       4     3       5   
13        1       1        0           2        0       5     2       3   
14        1       0        2           1        1       4     1       3   
15        1       1        0           1        0       4     2       2   
16        1       1        0           1        0       3     2       2   
17        1       1        0           3        0       5     1       4   
18        1       1        0           1        0       5     4       5   
19        1       1        1           1        0       3     3       5   
20        1       1        0           1        0       4     1       1   
21        1       1        1           1        0       5     1       5   
22        1       1        0           1        0       4     3       5   
23        1       1        0           2        0       5     4       5   
24        0       1        0           1        0       4     1       5   
25        1       1        0           1        0       1     3       5   
26        1       1        0           1        0       4     2       5   
27        1       1        0           1        0       2     4       1   
28        1       0        0           1        0       5     1       5   
29        1       1        0           1        1       4     5       5   
..      ...     ...      ...         ...      ...     ...   ...     ...   
619       1       1        0           2        1       4     3       3   
620       1       1        0           1        1       2     1       1   
621       0       1        1           2        0       3     2       3   
622       0       1        0           2        0       3     4       3   
623       1       1        0           2        1       4     2       5   
624       0       1        0           3        1       5     2       1   
625       1       1        1           2        1       5     2       4   
626       0       1        1           3        1       3     2       5   
627       0       1        1           3        1       4     3       3   
628       1       1        0           1        1       3     1       3   
629       0       1        0           1        0       3     3       1   
630       0       1        0           2        0       5     1       1   
631       0       1        0           4        0       4     2       4   
632       0       1        2           2        1       4     1       3   
633       0       1        0           1        0       5     4       2   
634       1       1        0           1        1       4     2       1   
635       0       1        0           1        0       4     3       1   
636       1       1        1           1        0       3     4       2   
637       0       1        0           2        1       4     3       5   
638       1       1        1           2        0       4     1       3   
639       0       1        0           2        0       4     3       5   
640       0       1        1 

In [13]:
target = student_per.finalgrade

In [14]:
#get features
data = student_per[['address', 'pstatus', 'guardian', 'traveltime', 'romantic', 'famrel', 'walc', 'health', 'absences']]

In [15]:
data

address pstatus guardian  traveltime romantic  famrel  walc  health  \
0         1       0        0           2        0       4     1       3   
1         1       1        1           1        0       5     1       3   
2         1       1        0           1        0       4     3       3   
3         1       1        0           1        1       3     1       5   
4         1       1        1           1        0       4     2       5   
5         1       1        0           1        0       5     2       5   
6         1       1        0           1        0       4     1       3   
7         1       0        0           2        0       4     1       1   
8         1       0        0           1        0       4     1       1   
9         1       1        0           1        0       5     1       5   
10        1       1        0           1        0       3     2       2   
11        1       1        1           3        0       5     1       4   
12        1       1        1           1        0       4     3       5   
13        1       1        0           2        0       5     2       3   
14        1       0        2           1        1       4     1       3   
15        1       1        0           1        0       4     2       2   
16        1       1        0           1        0       3     2       2   
17        1       1        0           3        0       5     1       4   
18        1       1        0           1        0       5     4       5   
19        1       1        1           1        0       3     3       5   
20        1       1        0           1        0       4     1       1   
21        1       1        1           1        0       5     1       5   
22        1       1        0           1        0       4     3       5   
23        1       1        0           2        0       5     4       5   
24        0       1        0           1        0       4     1       5   
25        1       1        0           1        0       1     3       5   
26        1       1        0           1        0       4     2       5   
27        1       1        0           1        0       2     4       1   
28        1       0        0           1        0       5     1       5   
29        1       1        0           1        1       4     5       5   
..      ...     ...      ...         ...      ...     ...   ...     ...   
619       1       1        0           2        1       4     3       3   
620       1       1        0           1        1       2     1       1   
621       0       1        1           2        0       3     2       3   
622       0       1        0           2        0       3     4       3   
623       1       1        0           2        1       4     2       5   
624       0       1        0           3        1       5     2       1   
625       1       1        1           2        1       5     2       4   
626       0       1        1           3        1       3     2       5   
627       0       1        1           3        1       4     3       3   
628       1       1        0           1        1       3     1       3   
629       0       1        0           1        0       3     3       1   
630       0       1        0           2        0       5     1       1   
631       0       1        0           4        0       4     2       4   
632       0       1        2           2        1       4     1       3   
633       0       1        0           1        0       5     4       2   
634       1       1        0           1        1       4     2       1   
635       0       1        0           1        0       4     3       1   
636       1       1        1           1        0       3     4       2   
637       0       1        0           2        1       4     3       5   
638       1       1        1           2        0       4     1       3   
639       0       1        0           2        0       4     3       5   
640       0       1        1 

In [16]:
#import statements
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

In [17]:
#Model: 50% for training and 50% for testing
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size=0.5, random_state=0)

In [18]:
x_train

address pstatus guardian  traveltime romantic  famrel  walc  health  \
4         1       1        1           1        0       4     2       5   
525       1       1        0           1        0       4     2       5   
501       1       1        1           1        0       4     5       5   
358       1       1        0           2        0       3     4       1   
426       0       1        0           2        0       5     3       5   
5         1       1        0           1        0       5     2       5   
141       0       1        0           4        0       5     1       3   
502       0       1        0           3        0       1     5       3   
135       1       0        1           1        0       3     4       5   
378       1       1        0           1        0       4     5       5   
584       0       1        0           2        0       4     1       5   
22        1       1        0           1        0       4     3       5   
589       1       1        1           1        0       5     1       3   
276       1       1        0           3        0       4     1       4   
284       1       1        0           1        0       3     5       5   
270       1       1        0           1        0       5     2       5   
622       0       1        0           2        0       3     4       3   
281       1       1        0           1        0       4     4       5   
220       1       0        0           1        0       2     2       4   
590       1       1        0           3        1       3     2       5   
320       1       1        1           1        1       2     1       4   
120       1       1        0           1        0       3     2       1   
81        1       1        0           1        0       5     2       5   
637       0       1        0           2        1       4     3       5   
616       1       1        1           2        1       3     2       3   
354       1       1        0           2        0       5     2       1   
630       0       1        0           2        0       5     1       1   
624       0       1        0           3        1       5     2       1   
160       1       1        1           1        1       2     4       1   
634       1       1        0           1        1       4     2       1   
..      ...     ...      ...         ...      ...     ...   ...     ...   
543       0       1        1           3        1       3     3       5   
544       0       1        1           2        1       5     3       5   
265       0       1        0           2        0       4     3       5   
288       1       0        0           1        1       4     3       5   
423       1       1        1           2        1       4     3       5   
147       1       1        0           2        0       4     1       5   
177       1       1        1           1        0       5     4       2   
99        1       1        0           1        0       5     1       3   
448       0       1        0           2        1       4     1       4   
431       0       1        1           1        1       4     2       5   
115       1       1        1           1        0       5     2       5   
72        0       1        0           1        1       3     4       5   
537       1       0        0           1        0       4     2       5   
639       0       1        0           2        0       4     3       5   
174       0       1        0           2        1       3     2       5   
87        1       1        0           1        0       5     3       1   
551       1       1        1           2        0       4     2       1   
486       1       1        1           1        0       4     4       3   
314       0       1        0           1        1       3     2       1   
396       1       1        0           1        1       4     3       5   
600       0       1        1           3        0       4     4       4   
472       0       1        1 

In [19]:
x_train.shape

(324, 9)

In [20]:
y_train

4      2
525    3
501    2
358    3
426    2
5      2
141    2
502    1
135    2
378    3
584    2
22     2
589    2
276    3
284    1
270    3
622    1
281    2
220    2
590    1
320    2
120    2
81     1
637    0
616    2
354    3
630    3
624    1
160    2
634    3
      ..
543    1
544    2
265    3
288    2
423    2
147    2
177    1
99     2
448    3
431    2
115    2
72     2
537    2
639    0
174    1
87     3
551    2
486    2
314    3
396    3
600    2
472    3
70     2
599    2
277    2
9      2
359    3
192    2
629    1
559    2
Name: finalgrade, Length: 324, dtype: int64

In [21]:
y_train.shape

(324L,)

In [22]:
x_test.shape

(325, 9)

In [23]:
y_test.shape

(325L,)

In [24]:
clf = DecisionTreeClassifier()

In [25]:
#train first model
fit_1 = clf.fit(x_train, y_train)

In [26]:
y_pre = fit_1.predict(x_test)

In [27]:
y_pre.shape

(325L,)

In [28]:
#create the confusion_matrix for model 1
cm_1 = confusion_matrix(y_test, y_pre)

In [29]:
print cm_1

[[  0   1   7   3]
 [  0   8  33   4]
 [  6  28 122  51]
 [  1   6  39  16]]


In [30]:
#create classification_report for model 1
print classification_report(y_test, y_pre)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.19      0.18      0.18        45
           2       0.61      0.59      0.60       207
           3       0.22      0.26      0.24        62

   micro avg       0.45      0.45      0.45       325
   macro avg       0.25      0.26      0.25       325
weighted avg       0.45      0.45      0.45       325



In [32]:
#create classification error rate
accuracy_1 = accuracy_score(y_test, y_pre, normalize=False) / float(y_test.size)

In [33]:
print accuracy_1

0.4492307692307692


In [34]:
#train model 2 with 60% for training and 40% testing
a_train, a_test, b_train, b_test = train_test_split(data, target, test_size=0.4, random_state=0)

In [35]:
a_train.shape

(389, 9)

In [36]:
b_train.shape

(389L,)

In [37]:
a_test.shape

(260, 9)

In [38]:
b_test.shape

(260L,)

In [39]:
#train model 2
fit_2 = clf.fit(a_train, b_train)

In [40]:
b_pre = fit_2.predict(a_test)

In [41]:
b_pre.shape

(260L,)

In [42]:
#create confusion matrix for model 2
cm_2 = confusion_matrix(b_test, b_pre)

In [43]:
print cm_2

[[ 0  2  4  2]
 [ 1  5 26  3]
 [ 3 30 91 43]
 [ 1  6 31 12]]


In [44]:
#create a classification report
print classification_report(b_test, b_pre)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         8
           1       0.12      0.14      0.13        35
           2       0.60      0.54      0.57       167
           3       0.20      0.24      0.22        50

   micro avg       0.42      0.42      0.42       260
   macro avg       0.23      0.23      0.23       260
weighted avg       0.44      0.42      0.43       260



In [45]:
#Create classification error rate
accuracy_2 = accuracy_score(b_test, b_pre, normalize=False) / float(b_test.size)

In [46]:
print accuracy_2

0.4153846153846154


In [47]:
#train model 3 with 80% for training and 20% for testing
s_train, s_test, t_train, t_test = train_test_split(data, target, test_size=0.2, random_state=0)

In [48]:
s_train.shape

(519, 9)

In [49]:
t_train.shape

(519L,)

In [50]:
s_test.shape

(130, 9)

In [51]:
t_test.shape

(130L,)

In [52]:
#train model 2
fit_3 = clf.fit(s_train, t_train)

In [53]:
t_pre = fit_3.predict(s_test)

In [55]:
t_pre.shape

(130L,)

In [56]:
#create the confusion matrix for model 3
cm_3 = confusion_matrix(t_test, t_pre)

In [57]:
print cm_3

[[ 0  1  0  0]
 [ 0  4  8  2]
 [ 1 22 50 19]
 [ 2  3 10  8]]


In [58]:
#create a classification report
print classification_report(t_test, t_pre)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.13      0.29      0.18        14
           2       0.74      0.54      0.62        92
           3       0.28      0.35      0.31        23

   micro avg       0.48      0.48      0.48       130
   macro avg       0.29      0.29      0.28       130
weighted avg       0.58      0.48      0.52       130



In [59]:
#Create a classification error rate
accuracy_3 = accuracy_score(t_test, t_pre, normalize=False) / float(t_test.size)

In [60]:
print accuracy_3

0.47692307692307695
